###########
### Short. Just read in, writes out
### for testing installation
############
pluginDir: ${f_pluginDir:/data/foundry/consumer_plugins/plugins}
database:
    host: ${f_mongodb_host:localhost}
    port: 27017
    db: ${f_mongo_db:cinergi}
    collection: ${f_mongodb_collection:records}
    user: ${f_mongobd_user:pipeline}
    pwd: ${f_mongodb_pwd:example}
mq:
    brokerURL: ${f_brokerURL:tcp://servicebus:61616?wireFormat.maxInactivityDuration=0}

workflow:
    "Cinergi Workflow":
        - uuidGen
        - export

consumers:
    - uuidGen:
         class: org.neuinfo.foundry.consumers.jms.consumers.plugins.DocIDAssigner
         status: id_assigned
    - export:
         class: "org.neuinfo.foundry.consumers.jms.consumers.plugins.WAFExporter"
         status: finished  
         outDirectory: ${f_waf_outDirectory:/tmp/waf}






