pluginDir: "data/foundry/consumer_plugins/plugins"
database:
    host: 10.128.10.165
    port: 27017
    db: cinergiStage
    user: reoot
    pwd: "example!"
    collection: records
mq:
    brokerURL: "tcp://localhost:61616"

workflow:
    "Cinergi Workflow":
        - uuidGen
        - spatial
        - keyword
        - export

consumers:
    - uuidGen:
         class: org.neuinfo.foundry.consumers.jms.consumers.plugins.DocIDAssigner
         status: id_assigned
    - spatial:
         class: org.neuinfo.foundry.consumers.jms.consumers.plugins.SpatialEnhancer2
         status: spatially_enhanced
    - keyword:
         class: org.neuinfo.foundry.consumers.jms.consumers.plugins.KeywordEnhancer2
         status: keyword_enhanced
         serviceURL: "http://ec-scigraph.sdsc.edu:9000"
         stopwordsUrl: "file:///data/cinergi/stopwords.txt"
         useNER: false
    - org:
         class: "org.neuinfo.foundry.consumers.jms.consumers.plugins.OrganizationEnhancer2"
         status: org_enhanced
    - export:
         class: "org.neuinfo.foundry.consumers.jms.consumers.plugins.WAFExporter"
         status: finished  
         outDirectory: "/tmp/waf"





